name: Manish Yadav
url: http://manishyadav.dev
designation: Software Engineer
baseurl: /
about_me: An organized individual eager for opportunities to support learning in software development and
                    web development. If you see that I can flourish in your team, contact me.